### ISSUE TITLE
log when can't find a version for extension

### ISSUE THREAD

**Issue by teto** [helsinki-systems/nc4nix#11]
I ran the generate.sh from nixpkgs to add the extension
https://apps.nextcloud.com/apps/les_pas_photo_app_for_android_phone

generate.sh doesnt add the extension, i suppose because the previous page doesnt list any version contrary to https://apps.nextcloud.com/apps/maps for instance where you can see all the downloads.
What bothers me (after removing the `rm *.log` call) is that no log is generated. I would expect the software to tell me it couldn't find the app ! )
```
2023/08/12 18:50:42 Writing 27-new.json
2023/08/12 18:50:42 Replacing 27.json with 27-new.json
2023/08/12 18:50:42 Writing 27-new.log
2023/08/12 18:50:42 Replacing 27.log with 27-new.log
2023/08/12 18:50:42 Finished processing version 27.0.1
```

**Comment by leonklingele** [comment]
Unfortunately, the Nextcloud App Store API doesn't return any information for such apps which do not distribute downloads through the Nextcloud App Store. There is no way for us to get to know about such apps except parsing the Nextcloud App Store Web UI which we really want to avoid.

@teto thanks for reporting this! Maybe you can file a feature request on the Nextcloud project? :)
